name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: PyInstaller Action
      uses: CodeByAidan/pyinstaller-action@v1.3
      with:
        spec: Ghost.spec
        requirements: requirements.txt
        options: --onefile --hidden-import=faker --hidden-import=pypresence --hidden-import=requests --add-data=data/*:data/ --add-data=data/fonts/*:data/fonts/ main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ghost-Windows
        path: dist/

  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fix brew packages
      run: |
        brew install gettext
        brew link --force gettext

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: PyInstaller Action
      uses: CodeByAidan/pyinstaller-action@v1.3
      with:
        spec: Ghost.spec
        requirements: requirements.txt
        options: --onefile --hidden-import=faker --hidden-import=pypresence --hidden-import=requests --add-data=data/*:data/ --add-data=data/fonts/*:data/fonts/ main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ghost-Mac
        path: dist/

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: PyInstaller Action
      uses: CodeByAidan/pyinstaller-action@v1.3
      with:
        spec: Ghost.spec
        requirements: requirements.txt
        options: --onefile --hidden-import=faker --hidden-import=pypresence --hidden-import=requests --add-data=data/*:data/ --add-data=data/fonts/*:data/fonts/ main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ghost-Linux
        path: dist/
